### ISSUE TITLE
Broken link for Node-RED starter pack documentation

### ISSUE THREAD

**Issue by gabriele-decapoa** [IBM-Bluemix-Docs/starters#11]
Clicking on "View docs" link on "create" page (image below), I will be redirected to a broken page instead of https://github.com/IBM-Bluemix-Docs/starters/blob/master/Node-RED/nodered.md.

![node-red_starter_-_ibm_cloud](https://user-images.githubusercontent.com/3875427/50633406-74ea8080-0f4b-11e9-9cde-380b606bb044.jpg)

This is the page that I see:
![ibm_cloud_docs](https://user-images.githubusercontent.com/3875427/50633447-9b102080-0f4b-11e9-925e-0dadf1d66ef7.jpg)

Is it possible to fix the link?

**Comment by bclerico** [comment]
In addition, the page referenced above (https://github.com/IBM-Bluemix-Docs/starters/blob/master/Node-RED/nodered.md) mentions "Start Coding > Download Starter Code" but that option does not exist on the actual service instance.

**Comment by gabriele-decapoa** [comment]
Issue solved, I am closing this.
